### get kategória
GET http://localhost:3000/categories
Content-Type: application/json

### get kategória by id
GET http://localhost:3000/categories/1
Content-Type: application/json

### delete kategória by id
DELETE http://localhost:3000/categories/6
Content-Type: application/json

### post new kategoria
POST http://localhost:3000/categories
Content-Type: application/json

{
    "nev": "Italok"
}

### update new kategoria
PATCH http://localhost:3000/categories/3
Content-Type: application/json

{
    "nev": "Dessz ertek"
}









### get forgalom
GET http://localhost:3000/traffic
Content-Type: application/json

### get forgalom by id
GET http://localhost:3000/traffic/250
Content-Type: application/json

### post new traffic
POST http://localhost:3000/traffic
Content-Type: application/json

{
    "termek": "asd",
    "vevo": "valaki",
    "kategoriaId": 2,
    "egyseg": "db",
    "nettoar": 42069,
    "mennyiseg": 3,
    "kiadva": 1
}

### delete traffic by id
DELETE http://localhost:3000/traffic/259
Content-Type: application/json

### update new traffic
PATCH http://localhost:3000/traffic/3
Content-Type: application/json

{
    "nev": "Dessz ertek"
}







### get forgalom
GET http://localhost:3000/statistics
Content-Type: application/json