@host = http://localhost
@port = 3000
@url = {{host}}:{{port}}


### get kategória
GET {{url}}/categories
Content-Type: application/json

### get kategória by id
GET http://localhost:3000/categories/1
Content-Type: application/json

### delete kategória by id
DELETE http://localhost:3000/categories/6
Content-Type: application/json

### post new kategoria
POST http://localhost:3000/categories
Content-Type: application/json

{
    "nev": "hihihi"
}

### update new kategoria
PATCH http://localhost:3000/categories/3
Content-Type: application/json

{
    "nev": "Dessz ertek"
}









### get forgalom
GET http://localhost:3000/traffic
Content-Type: application/json

### get forgalom by id
GET http://localhost:3000/traffic/250
Content-Type: application/json

### post new traffic
POST http://localhost:3000/traffic
Content-Type: application/json

{
    "termek": "Vodka",
    "vevo": "Orosz",
    "kategoriaId": 3,
    "egyseg": "dl",
    "nettoar": 700,
    "mennyiseg": 3,
    "kiadva": 1
}

### delete traffic by id
DELETE http://localhost:3000/traffic/259
Content-Type: application/json

### update new traffic
PATCH http://localhost:3000/traffic/262
Content-Type: application/json

{
    "termek": "Wawo",
    "vevo": "Owaw",
    "kategoriaId": 2,
    "egyseg": "dl",
    "nettoar": 515,
    "mennyiseg": 3,
    "kiadva": 1
}







### get forgalom
GET http://localhost:3000/statistics
Content-Type: application/json










### GET customers 
GET http://localhost:3000/customers 
Content-Type: application/json

### POST customer 
POST http://localhost:3000/customers
Content-Type: application/json

{
"vevoNev": "András"
} 
### GET customer by ID 
GET http://localhost:3000/customers/2
Content-Type: application/json 


### UPDATE customer by ID 
PATCH http://localhost:3000/customers/2
Content-Type: application/json

{
"vevoNev": "Jenő"
}

### DELETE customer by ID 
DELETE http://localhost:3000/customers/1 
Content-Type: application/json
















### GET products
GET http://localhost:3000/products
Content-Type: application/json

### GET one product by id
GET http://localhost:3000/products/2
Content-Type: application/json

### DELETE product by id
DELETE http://localhost:3000/products/1
Content-Type: application/json

### POST new product
POST http://localhost:3000/products
Content-Type: application/json

{
    "termek":"Mákos bejgli",
    "kategoriaNev":"Desszertek",
    "egyseg": "szelet",
    "nettoAr": 200
}

### UPDATE product by id
PATCH http://localhost:3000/products/2
Content-Type: application/json

{
    "termek":"Alma",
    "kategoriaNev":"Ételek",
    "egyseg": "db",
    "nettoAr": 2
}